remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//thomasvargiu.github.io/fp-ts-ix/"
  "API Reference":
    - "//thomasvargiu.github.io/fp-ts-ix/modules/"
  'fp-ts-ix on GitHub':
    - 'https://github.com/thomasvargiu/fp-ts-ix'
